booking_app/urls.py
from django.urls import path
from . import views
from booking_app.views import ModifyView, NewRoomView, DeleteView, ReservationView, SearchView

app_name = 'booking'

urlpatterns = [
    path('', views.index, name='home'),
    path('room/<int:id>/', views.room, name='room'),
    path('room/new', NewRoomView.as_view(), name='new-room'),
    path('room/modify/<int:id>', ModifyView.as_view(), name='modify'),
    path('room/delete/<int:id>', DeleteView.as_view(), name='delete'),
    path('room/reservation/<int:id>', ReservationView.as_view(), name='reservation'),
    path('search/', SearchView.as_view(), name='search'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booking_app.urls'))
]

booking_app/models.py
from django.db import models

# Create your models here.
class Room(models.Model):
    name = models.CharField(max_length=100)
    capacity = models.IntegerField()
    projector = models.BooleanField(default=True)
    
    def __str__(self):
        return self.name

class Reservation(models.Model):
    room = models.ManyToManyField(Room)
    date = models.DateField()
    comment = models.TextField()

    def __str__(self):
        for r in self.room.all():
            return "Tarikh tempahan: {}, bilik: {}".format(self.date, r.name)
    

booking_app/views.py
from django.shortcuts import render, redirect
from .models import Room, Reservation
from datetime import datetime
from django.views import View



# Create your views here.

today = datetime.today().strftime("%Y-%m-%d")


def index(request):
    rooms = Room.objects.all()
    status = {}

    for room in rooms:
        if room.reservation_set.filter(date=today):
            status[room.id] = "Sibuk"
        else:
            status[room.id] = "Free"

            ctx = {
                "rooms": rooms,
                "status": status,
            }
            return render(request, "booking/index.html", ctx)

def room(request, id):
    id = int(id)
    room = Room.objects.get(pk=id)
    reservations = room.reservation_set.filter(date__gte=today).order_by('date')
    rooms = Room.objects.all()
    if room.projector == True:
        projector = "YA"
    else:
        projector = "TIDAK"
    ctx = {
        "room": room,
        "projector": projector,
        "reservations":reservations,
        "rooms":rooms,
    }
    return render(request, 'booking/room.html', ctx)

class NewRoomView(View):
    
    def get(self, request):
        return render(request, 'booking/new_room.html')
    
    def post(self, request):
        
        try:
            name = request.POST.get("name")
            capacity = request.POST.get("capacity")
            projector = request.POST.get("projector")
            proj = True if projector == 'True' else False
            
            Room.objects.create(name=name, capacity=capacity, projector=proj)

            return redirect("/")

        except Exception as e:
            message = "Data tidak betul: {}".format(e)
            ctx = {
                "message":message,
            }
            return render(request, "booking/new_room.html", ctx)

class ModifyView(View):
    def get(self, request, id):
        room = Room.objects.get(pk=id)
        ctx = {
            "room": room,
        }
        return render(request, 'booking/modify.html', ctx)
    
    def post(self, request, id):
        name = request.POST.get("name")
        capacity = request.POST.get("capacity")
        projector = True if request.POST.get('projector') else False
        room = Room.objects.get(pk=id)
        try:
            room.name =name
            room.capacity = capacity
            room.projector = projector
            room.save()
            return redirect('/')
        except Exception as e:
            message = "Data tidak betul: {}".format(e)
            ctx = {
                "message": message,
                "room": room,
            }
            return render(request, 'booking/modify.html', ctx)

        
class DeleteView(View):
    def get(self, request, id):
        room = Room.objects.get(pk=id)
        ctx = {
            "room":room,
        }
        return render(request, 'booking/delete.html', ctx)

    def post(self, request, id):
        action = request.POST.get('submit')

        if action == "YA":
            room = Room.objects.get(pk=id)
            room.delete()

        return redirect("/")

class ReservationView(View):
    
    def get(self, request, id):
        room = Room.objects.get(pk=id)       
        reservations = room.reservation_set.filter(date__gte=today).order_by('date')
        ctx = {
            "room":room,
            "reservations": reservations
        }
        return render(request, 'booking/reservation.html', ctx)

    def post(self, request, id):
        room = Room.objects.get(pk=id)
        reservations = room.reservation_set.filter(date__gte=today).order_by('date')    
        try:
            date = request.POST.get('date')
            comment = request.POST.get('comment')
            message = ""

            if room.reservation_set.filter(date=date):
                message = "Bilik sudah diduduki hari itu"
            elif date < today:
                message = 'Tarikh yang dipilih tidak boleh dari masa lalu'
            if(message == "Bilik sudah diduduki hari itu" or message == "Tarikh yang dipilih tidak boleh dari masa lalu" ):
                ctx = {
                    'room':room,
                    'reservations':reservations,
                    'message':message,
                }
                return render(request, 'booking/reservation.html')
            reservation = Reservation.objects.create(date=date, comment=comment)
            reservation.room.add(room)
            
        except Exception as e:
            message = 'data tidak betul: {}'.format(e)
            ctx = {
                'message':message,
                'room':room,
                'reservations':reservations,
            }
            return render(request, 'booking/reservation.html', ctx)

        if room.projector == True:
            projector = "YA"
        else:
            projector = "TIDAK"
            message = """Terima kasih! Saya telah menempah bilik: {} pada: {}""".format(room.name, date)
        ctx = {
            'room':room,
            'projector':projector,
            'reservations':reservations,
            'message':message,
        }
        return render(request, 'booking/room.html', ctx)

class SearchView(View):
    def get(self, request):
        room = request.GET.get('room')
        capacity = request.GET.get('capacity')
        date = request.GET.get ('date')
        projector = True if request.GET.get('projector') else False
        
        result1 = Room.objects.exclude(reservation__date=date)

        if room == "":
            result2 = result1
        else:
            result2 = result1.filter(name__icontains=room)

        if capacity !="":
            result3 = result2.filter(capacity__gte=int(capacity))
        else:
            result3 = result2
            
        if projector:
            result4 = result3.filter(projector=projector)
        else:
            result4 = result3

        ctx = {
            'results': result4,
            'date': date,
        }
        return render(request, 'booking/search.html', ctx)
            

booking_app/templates/booking/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
          crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-sm bg-info navbar-light">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link lead text-dark" href="{% url 'booking:home' %}">HOME </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link lead text-dark" href="{% url 'booking:new-room' %}">DEWAN BARU</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link lead text-dark" href="/bookconfroom/#search">CARI BILIK </a>
                </li>
            </ul>
        </nav>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

booking_app/templates/booking/delete.html
{% extends 'booking/base.html' %}

{% block title %}Padam bilik{% endblock %}

{% block content %}
    <br/>
    <h2>Adakah anda pasti mahu memadamkan bilik itu?: {{ room.name }}</h2>
    <form method="POST" action="#">
    {% csrf_token %}
        <input class="btn btn-success" type="submit" name="submit" value="YA">
        <input class="btn btn-danger" type="submit" name="submit" value="TIDAK">
    </form>
{% endblock %}

booking_app/templates/booking/index.html
{% extends 'booking/base.html' %}

{% block title %}Bilik persidangan{% endblock %}

{% block content %}
    <br/>
    <h2>Bilik persidangan untuk ditempah</h2>
    <table class="table table-striped table-bordered">
        <tr>
            <thead class="thead lead">
                <th>NAMA BILIK</th>
                <th>KAPASITI</th>
                <th>STATUS</th>
                <th>UBAHSUAI</th>
                <th>PADAM</th>
            </thead>
        </tr>
        {% for room in rooms %}
        <tr>
            <td><a href="{% url 'booking:room' room.id %}">{{ room.name }}</a></td>
            <td>{{ room.capacity }}</td>
            {% for k,v in status.items %}
                {% if room.id == k %}
                    <td{% if v == "Free" %} class="text-success"
                    {% else %} class="text-danger" {% endif %}>{{ v }}</td>
                {% endif %}
            {% endfor %}
            <td><a href="{% url 'booking:modify' room.id %}"><button class="btn btn-warning">ubah suai</button></a></td>
            <td><a href="{% url 'booking:delete' room.id %}"><button class="btn btn-danger">padam</button></a></td>
        </tr>
        {% endfor %}
    </table>
    <a href="{% url 'booking:new-room' %}">
        <button class="btn btn-success">Buat bilik persidangan baharu</button>
    </a><br/><br/>
    <div class="jumbotron">
        <h3>CARI BILIK YANG DISEDIAKAN</h3>
        <br/>
        <form id="search" method="get" action="{% url 'booking:search' %}">
            <label>NAMA BILIK
                <input type="text" name="room">
            </label><br/>
            <label>KAPASITI MINIMUM
                <input type="number" name="capacity">
            </label><br/>
            <label>TARIKH TEMPAHAN
                <input type="date" name="date" required="required">
            </label><br/>
            <label>PROJEKTOR
                <input type="checkbox" name="projector">
            </label><br/>
                <input type="submit" value="Cari" class="btn btn-warning">
        </form>
    </div>

{% endblock %}

booking_app/templates/booking/modify.html
{% extends 'booking/base.html' %}

{% block title %}Modify room{% endblock %}

{% block content %}
    <br/>
    <h2>Pengubahsuaian bilik persidangan: {{ room.name }}</h2>
    <p class="text-danger">{{ message }}</p>
    <form method="POST" action="#">
    {% csrf_token %}
        <label>Bilik
            <input type="text" name="name" value="{{ room.name }}" class="form-control">
        </label>
        <br/>
        <label>Kapasiti:
            <input type="number" name="capacity", value="{{ room.capacity }}" class="form-control">
        </label>
        <br/>
        {% if room.projector == True %}
        <input type="checkbox" name="projector" checked="checked"> PROJEKTOR
        {% else %}
        <input type="checkbox" name="projector"> PROJEKTOR
        {% endif %}
        <br/>
        <br/>
        <input class="btn btn-warning" type="submit" value="UBAHSUAI">
    </form>
{% endblock %}

booking_app/templates/booking/new_room.html
{% extends 'booking/base.html' %}

{% block title %}Tambah bilik{% endblock %}

{% block content %}

    <br/>
    <h2>Buat Bilik Persidangan Baharu</h2>
    <p class="text-danger">{{ message }}</p>
    <form method="POST" action="#">
    {% csrf_token %}
        <label>NAMA BILIK
            <input type="text" name="name" class="form-control" required="required">
        </label><br/>
        <label>KAPASITI BILIK
            <input type="number" name="capacity" placeholder="np. 50"
                   class="form-control" required="required">
        </label><br/>
        <label>ADA PROJEKTOR:
            <input type="radio" name="projector" value="True">YA
            <input type="radio" name="projector" value="False">TIDAK
        </label><br/>
        <input class="btn btn-success" type="submit" value="CIPTA">
    </form>

{% endblock %}

booking_app/templates/booking/reservation.html
{% extends 'booking/base.html' %}

{% block title %}Reservation{% endblock %}

{% block content %}
    <br/>
    <table class="table table-bordered table-striped">
        <tr>
            <td>Bilik :</td>
            <td>{{ room.name|upper }}</td>
        </tr>
        <tr>
            <td>Tarikh sibuk :</td>
            <td>
                {% for book in reservations %}
                {{ book }}<br/>
                {% endfor %}
            </td>
        </tr>
    </table>

    <h2>Tempah Tarikh Anda - {{ room.name }}</h2>
    <p class="text-danger">{{ message }}</p>

    <form method="post" action="#">
    {% csrf_token %}
        <label>Tarikh:
            <input type="date" name="date" required="required">
        </label><br/>
        <label>Detail Tambahan:<br/>
            <textarea name="comment" class="form-control">detail</textarea>
        </label><br/>
        <input type="submit" name="submit" value="Tempah" class="btn btn-success">
    </form> <br>
    <a href="{% url 'booking:room' room.id %}">
            <button class="btn btn-warning">Kembali ke pemandangan bilik</button></a>
{% endblock %}

booking_app/templates/booking/room.html
{% extends 'booking/base.html' %}

{% block title %}Room details{% endblock %}

{% block content %}
    <br/>
    <table class="table table-bordered table-striped">
        <tr>
            <td>Bilik persidangan</td>
            <td class="lead">{{ room.name|upper }}</td>
        </tr>
        <tr>
            <td>Kapasiti</td>
            <td>{{ room.capacity }}</td>
        </tr>
        <tr>
            <td>Projektor</td>
            <td>{{ projector }}</td>
        </tr>
        <tr>
            <td>Bilik itu diduduki</td>
            <td>{% for reservation in reservations %}{{ reservation }}<br/>{% endfor %}</td>
        </tr>
        <tr>
            <td>Menempah bilik</td>
            <td>
                <a href="{% url 'booking:reservation' room.id %}">
                <button class="btn btn-success">Tempah sekarang</button></a>
            </td>
        </tr>
    </table>
    <br/>

    {% if room.id > 1 %}
        <a href="{% url 'booking:room' room.id|add:'-1' %}">
            <button class="btn btn-warning">Bilik petang</button>
        </a>
    {% else %}
        <a href="{% url 'booking:room' rooms|length %}">
            <button class="btn btn-warning">Bilik petang</button>
        </a>
    {% endif %}

    {% if room.id < rooms|length %}
        <a href="{% url 'booking:room' room.id|add:'1' %}">
            <button class="btn btn-warning">Bilik lain</button>
        </a>
    {% else %}
        <a href="{% url 'booking:room' 1 %}">
            <button class="btn btn-warning">Bilik lain</button>
        </a>
    {% endif %}

    <br/>
    <p class="text-danger lead">{{ message }}</p>
{% endblock %}

booking_app/templates/booking/search.html
{% extends "booking/base.html" %}

{% block title %}Cari{% endblock %}

{% block content %}
<br/>
<h2>Bilik tersedia tepat pada masanya: {{ date }} memenuhi keperluan:</h2>
<br/>
<table class="table table-bordered table-striped">
    <thead class="lead">
        <tr>
            <th>BILIK:</th>
            <th>KAPASITI:</th>
            <th>PROJEKTOR:</th>
        </tr>
    </thead>
    <tbody>
    {% for result in results %}
        <tr>
            <td><a href="{% url 'booking:room' result.id %}">{{ result.name }}</a></td>
            <td>{{ result.capacity }}</td>
            <td>
                {% if result.projector == True %}
                YA
                {% else %}
                TIDAK
                {% endif %}
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<br/>
<p class="text-danger">*Mengklik pada nama bilik akan membawa anda ke halaman tempahan</p>


{% endblock %}